import { Geist } from "next/font/google";
import "./globals.css";

import Header from "./component/Header";
import Footer from "./component/Footer";

import { getNavigation } from "./lib/navigation";
import { getGlobal } from "./lib/global";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Qbix",
  description: "Generated by setoo solutions",
  icons: { icon: "/Logo.png" },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navigation = await getNavigation();
  const globalData = await getGlobal();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased bg-white`}>
        <Header menu={navigation} global={globalData} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
