import { getDesignSystem } from "@/app/lib/design";
import { generateCssVariables } from "@/app/helper/styleGenerator";

import { Geist } from "next/font/google";
import "../globals.css";

import Header from "../component/Header";
import Footer from "../component/Footer";

import { getNavigation } from "../lib/navigation";
import { getGlobal } from "../lib/global";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

import { Metadata } from 'next';

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }): Promise<Metadata> {
  const { lang } = await params;

  return {
    title: {
      default: "Qbix",
      template: "%s | Qbix"
    },
    description: "Generated by setoo solutions",
  };
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const navigation = await getNavigation(lang);
  const globalData = await getGlobal(lang);
  const designSystem = await getDesignSystem(lang);
  return (
    <html lang={lang}>
      <head>
        {designSystem && (
          <style
            dangerouslySetInnerHTML={{
              __html: generateCssVariables(designSystem),
            }}
          />
        )}
      </head>
      <body className={`${geistSans.variable} antialiased bg-white`}>
        <Header menu={navigation} global={globalData} locale={lang} />
        {children}
        <Footer locale={lang} />
      </body>
    </html>
  );
}
